/* 
 * PROYECTO G-FUNK
 * MATERIA: PROGRAMACIÓN WEB S6C
 * CARRERA: INGENIERÍA EN SISTEMAS COMPUTACIONALES
 * FECHA: 15/05/2020
 * TECNM  CAMPUS HERMOSILLO
*/

CREATE DATABASE G_FUNK
GO


USE G_FUNK
GO

CREATE TABLE PRODUCTOS(
	IdProducto		INT IDENTITY	(1, 1)	PRIMARY KEY NOT NULL,
	Nombre			VARCHAR			(100)	NOT NULL, 
	Descripcion		VARCHAR			(100)	NOT NULL, 
	Marca			VARCHAR			(100)	NOT NULL,
	Precio			MONEY					NOT NULL,
	Stock			INT						NOT NULL
)


-- PRODUCTOS DEL LA PESTAÑA WEB 'STYLE'--

INSERT INTO PRODUCTOS VALUES 
('AIR MAX ALPHA SAVAGE'   ,'TENIS HOMBRE'    ,'NIKE'     ,2199.00   ,50),
('SPORTSWEATR SNEAKER'    ,'PLAYERA HOMBRE'  ,'NIKE'     ,599.00    ,25),
('SENSEBOUNCE + STREET'   ,'TENIS HOMBRE'    ,'ADDIDAS'  ,1999.00   ,60)


SELECT * FROM PRODUCTOS
--------------------------------------------------------------------------
			-------PROCEDIMIENTOS ALMACENADOS------


--- PROCEDIMIENTO ALMACENADO MOSTRAR MOSTRAR/BUSCAR EN TIEMPO REAL
CREATE PROC SP_MOSTRAR_X_PRODUCTOS
	@IdProducto INT
AS
SELECT * FROM PRODUCTOS
WHERE IdProducto = @IdProducto
GO


EXEC SP_MOSTRAR_X_PRODUCTOS 1


-- POR PRODUCTO
CREATE PROC SP_MOSTRAR_TODO_PRODUCTO
	AS
SELECT * FROM PRODUCTOS
GO

EXEC SP_MOSTRAR_TODO_PRODUCTO


--- PROCEDIMIENTO ALMACENADO INSERTAR PRODUCTO
CREATE PROC SP_INSERTAR_PRODUCTOS
	@Nombre VARCHAR (100),
	@Descripcion VARCHAR (100),
	@Marca VARCHAR (100),
	@Precio FLOAT,
	@Stock INT
AS
INSERT INTO PRODUCTOS VALUES (@Nombre, @Descripcion, @Marca, @Precio, @Stock)
GO

EXEC SP_INSERTAR_PRODUCTOS 'AIR JORDAN', 'TENIS UNISEX', 'NIKE', 2399, 5
SELECT * FROM PRODUCTOS


--- PROCEDIMIENTO ALMACENADO EDITAR PRODUCTO
CREATE PROC SP_EDITAR_PRODUCTOS
	@Nombre			VARCHAR (100),
	@Descripcion	VARCHAR (100),
	@Marca			VARCHAR (100),
	@Precio			float, 
	@Stock			INT,
	@IdProducto		INT
AS
UPDATE PRODUCTOS SET Nombre = @Nombre, Descripcion = @Descripcion, Marca = @Marca, Precio = @Precio, Stock = @Stock
WHERE IdProducto = @IdProducto
GO


EXEC SP_EDITAR_PRODUCTOS 'MAX ALPHA', 'TENIS HOMBRE', 'NIKE', 2000, 40, 1
SELECT * FROM PRODUCTOS


--- PROCEDIMIENTO ALMACENADO ELIMINAR PRODUCTO
CREATE PROC SP_ELIMINAR_PRODUCTO
	@IdProducto INT
AS
DELETE PRODUCTOS 
WHERE IdProducto = @IdProducto


EXEC SP_ELIMINAR_PRODUCTO 5   
SELECT * FROM PRODUCTOS 


--- PROCEDIMIENO ALMACENADO CREAR O ALMACENAR
CREATE PROC SP_CREAR_O_ALMACENAR 
	@IdProducto    INT,
	@Nombre        VARCHAR(100),
	@Descripcion   VARCHAR(100),
	@Marca         VARCHAR(100),
	@Precio		   FLOAT,
	@Stock		   INT
AS
BEGIN
	IF(@IdProducto = 0)
		BEGIN
			INSERT INTO PRODUCTOS(Nombre,Descripcion,Marca,Precio,Stock)
			VALUES (@Nombre, @Descripcion, @Marca, @Precio, @Stock)
		END
	ELSE
		BEGIN
			UPDATE PRODUCTOS SET Nombre = @Nombre, Descripcion = @Descripcion, Marca = @Marca, Precio = @Precio, Stock = @Stock
			WHERE @IdProducto = IdProducto
		END
END

drop proc SP_CREAR_O_ALMACENAR


/* ----------------------------- ACCESO ----------------------------*/

CREATE TABLE LOGIN(
USERNAME VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(50) NOT NULL
)

INSERT INTO LOGIN VALUES('ADMIN', '123')

CREATE PROC SP_ACCESO
	@username varchar(50) = 'ADMIN',
	@password varchar(50) = '123'
AS
BEGIN
SELECT * FROM LOGIN WHERE @username = USERNAME AND @password = PASSWORD
END
